### ISSUE TITLE
Move away from onig to regex

### ISSUE THREAD

**Issue by untitaker** [davidarmstronglewis/uap-rs#2]
Would you accept a patch that moves from onig to regex for performance? The go implementation uses a similar regex dialect and it seems that the uap-core project made their regexes compatible with that.

**Comment by untitaker** [comment]
@davidarmstronglewis

**Comment by untitaker** [comment]
nvm https://github.com/rust-lang/regex/issues/524

**Comment by untitaker** [comment]
checking if it's feasible to change the regexes in uap-core to avoid `||`

**Comment by hazel-ocean** [comment]
You can definitely take a look, but if you're looking for a pure Rust implementation this project might not be the best for your use-case since I am relying on upstream regexes from the UAParser project. I suppose there's nothing stopping you from supplying your own regexes and swapping out the Onig for Regex, but at that point you're probably better off looking at [Woothie](https://crates.io/crates/woothee).

**Comment by untitaker** [comment]
I was looking into upstreaming fixes to uaparser that make it possible to parse the regexes with the regex crate, but that seems like a monumental task now. Older versions of regexes.yaml work fine.

**Comment by hazel-ocean** [comment]
Thanks for looking into this. Let me know if you decide to keep going with this library or move to another :)

**Comment by untitaker** [comment]
I stopped putting time into this, the status quo is that we use this library despite onig.

For our WASM builds we have disabled the functionality that requires user agent parsing.

**Comment by untitaker** [comment]
#4 moves the library to fancy-regex
